# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170603_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learnhours',
            field=models.IntegerField(),
        ),
    ]
